"""
spectral_operator.evolution
===========================

Evolution operators and propagators.

This module contains tools for constructing and applying operator-induced
evolutions, including unitary-style propagators generated by Hamiltonian
operators.
"""

from __future__ import annotations

import numpy as np

from .algebra import LinearOperator, OperatorError

from scipy.linalg import expm


# ===========================================================================
# Propagators
# ===========================================================================

class Propagator:
    """
    Base class for operator propagators.
    """

    def __init__(self, operator: LinearOperator):
        if not isinstance(operator, LinearOperator):
            raise OperatorError("operator must be a LinearOperator.")

        if not operator.is_square:
            raise OperatorError("propagators require square operators.")

        self.operator = operator

    def matrix(self, t: float) -> np.ndarray:
        raise NotImplementedError

    def apply(self, vector, t: float) -> np.ndarray:
        v = np.asarray(vector)

        if v.ndim != 1:
            raise OperatorError("vector must be one-dimensional.")

        if len(v) != self.operator.cols:
            raise OperatorError("vector dimension does not match operator.")

        return self.matrix(t) @ v


# ===========================================================================
# Unitary Evolution
# ===========================================================================

class UnitaryEvolution(Propagator):
    """
    Evolution generated by exp(-i H t).
    """

    def matrix(self, t: float) -> np.ndarray:
        H = self.operator.matrix
        return expm(-1j * H * t)


# ===========================================================================
# Semigroup Evolution
# ===========================================================================

class SemigroupEvolution(Propagator):
    """
    Evolution generated by exp(t A).
    """

    def matrix(self, t: float) -> np.ndarray:
        A = self.operator.matrix
        return expm(t * A)


# ===========================================================================
# Evolution Analyzer
# ===========================================================================

class EvolutionAnalyzer:
    """
    High-level interface for studying operator-induced evolution.
    """

    def __init__(self, operator: LinearOperator):
        if not isinstance(operator, LinearOperator):
            raise OperatorError("operator must be a LinearOperator.")

        self.operator = operator

    def unitary(self) -> UnitaryEvolution:
        return UnitaryEvolution(self.operator)

    def semigroup(self) -> SemigroupEvolution:
        return SemigroupEvolution(self.operator)

    def propagate_unitary(self, vector, t: float) -> np.ndarray:
        return self.unitary().apply(vector, t)

    def propagate_semigroup(self, vector, t: float) -> np.ndarray:
        return self.semigroup().apply(vector, t)
